import { Flex, Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from './NavBar';
import Providers from './Providers';
import { fullHeightAndWidth } from './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en" className={fullHeightAndWidth}>
      <body className={`${inter.className} ${fullHeightAndWidth}`}>
        <Providers>
          <Theme
            appearance="dark"
            accentColor="blue"
            className={fullHeightAndWidth}
          >
            <Flex
              direction="column"
              gap="2"
              p="3"
              width={'100%'}
              height={'100%'}
            >
              <NavBar />
              {children}
            </Flex>
          </Theme>
        </Providers>
      </body>
    </html>
  );
}
